// Generates contracts/pool/src/poseidon_constants.rs from circomlib's 2-input Poseidon constants
// (as shipped by poseidon-lite), in Montgomery form for the contract's field arithmetic, plus the
// Merkle tree's empty-subtree values. The output is fixed by the Poseidon spec and is committed.
import { writeFileSync } from 'node:fs';
import { createRequire } from 'node:module';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { FIELD_SIZE, TREE_DEPTH, zeroValues } from '@occulta/framework/protocol';

const repo = resolve(dirname(fileURLToPath(import.meta.url)), '../..');
const require = createRequire(join(repo, 'package.json'));
const decode = (s: string): bigint => BigInt(`0x${Buffer.from(s, 'base64').toString('hex') || '0'}`);
const raw = require(join(repo, 'node_modules/poseidon-lite/constants/2.js')).default as { C: string[]; M: string[][] };

const mont = (x: bigint): bigint => (x << 256n) % FIELD_SIZE;
const limbs = (x: bigint): string => {
  const parts = [0, 1, 2, 3].map((i) => `0x${((x >> BigInt(64 * i)) & 0xffff_ffff_ffff_ffffn).toString(16).padStart(16, '0')}`);
  return `Fr([${parts.join(', ')}])`;
};
const be = (x: bigint): string => `U256::from_be_bytes(hex!("${x.toString(16).padStart(64, '0')}"))`;

const C = raw.C.map(decode);
const M = raw.M.map((row) => row.map(decode));
if (C.length !== 195 || M.length !== 3) throw new Error('unexpected Poseidon(2) constant sizes');

const out = [
  '// @generated by contracts/scripts/gen-poseidon.ts from circomlib Poseidon constants (t = 3). Do not edit.',
  'use crate::field::Fr;',
  'use alloy_primitives::U256;',
  'use hex_literal::hex;',
  '',
  '/// Round constants, Montgomery form.',
  `pub const C: [Fr; ${C.length}] = [`,
  ...C.map((c) => `    ${limbs(mont(c))},`),
  '];',
  '',
  '/// MDS matrix, Montgomery form.',
  'pub const M: [[Fr; 3]; 3] = [',
  ...M.map((row) => `    [${row.map((m) => limbs(mont(m))).join(', ')}],`),
  '];',
  '',
  `/// Empty-subtree hashes: ZEROS[i] is the root of an empty tree of height i.`,
  `pub const ZEROS: [U256; ${TREE_DEPTH + 1}] = [`,
  ...zeroValues(TREE_DEPTH).map((z) => `    ${be(z)},`),
  '];',
  '',
];
writeFileSync(join(repo, 'contracts/pool/src/poseidon_constants.rs'), out.join('\n'));
console.log('wrote contracts/pool/src/poseidon_constants.rs');
