//! Native tests: disputes replay real proofs generated by contracts/scripts/fixtures.ts.

use super::*;
use stylus_sdk::testing::TestVM;

const POOL: Address = Address::repeat_byte(0x0a);
const VERIFIER: Address = Address::repeat_byte(0x01);
const T0: u64 = 1_800_000_000;
const DAY: u64 = 86_400;

fn fixture() -> serde_json::Value {
    let path = std::path::Path::new(env!("CARGO_MANIFEST_DIR"))
        .join("../../circuits/build/fixtures/dispute.json");
    let text = std::fs::read_to_string(&path)
        .unwrap_or_else(|_| panic!("missing {} (run `npm run setup`)", path.display()));
    serde_json::from_str(&text).unwrap()
}

fn num(v: &serde_json::Value) -> U256 {
    U256::from_str_radix(v.as_str().unwrap(), 10).unwrap()
}

fn words<const N: usize>(v: &serde_json::Value) -> [U256; N] {
    v.as_array()
        .unwrap()
        .iter()
        .map(num)
        .collect::<Vec<_>>()
        .try_into()
        .unwrap()
}

fn bytes(v: &serde_json::Value) -> Bytes {
    Bytes::from(alloy_primitives::hex::decode(v.as_str().unwrap()).unwrap())
}

fn err_name(e: DisputeError) -> String {
    format!("{e:?}").split('(').next().unwrap().to_string()
}

fn setup(vm: &TestVM) -> Disputes {
    vm.set_block_timestamp(T0);
    let mut d = Disputes::from(vm);
    d.initialize(POOL, VERIFIER).unwrap();
    d
}

/// The pool answers isKnownRoot; the test VM returns the most recently registered mock, so it is
/// registered right before each submission.
fn pool_knows(vm: &TestVM, root: U256, known: bool) {
    let data = IPool::isKnownRootCall { root }.abi_encode();
    vm.mock_static_call(
        POOL,
        data,
        Ok(alloy_sol_types::SolValue::abi_encode(&known)),
    );
}

fn submit(vm: &TestVM, d: &mut Disputes, v: &serde_json::Value) -> Result<(), DisputeError> {
    let signals: [U256; 5] = words(&v["signals"]);
    pool_knows(vm, signals[0], true);
    d.submit_state(words(&v["proof"]), signals)
}

fn finalize(d: &mut Disputes, v: &serde_json::Value) -> Result<(), DisputeError> {
    d.finalize(
        words(&v["proof"]),
        words(&v["signals"]),
        bytes(&v["ciphertexts"]),
    )
}

fn reclaim(d: &mut Disputes, v: &serde_json::Value) -> Result<(), DisputeError> {
    d.reclaim(
        words(&v["proof"]),
        words(&v["signals"]),
        bytes(&v["ciphertexts"]),
    )
}

fn channel_nullifier(v: &serde_json::Value) -> U256 {
    num(&v["signals"][1])
}

#[test]
fn old_state_is_answered_by_the_latest_and_finalizes_after_the_fixed_deadline() {
    let vm = TestVM::default();
    let mut d = setup(&vm);
    let f = fixture();
    let cn = channel_nullifier(&f["submitOld"]);

    submit(&vm, &mut d, &f["submitOld"]).unwrap();
    let (pending, nonce, _, deadline) = d.dispute_of(cn);
    assert!(pending);
    assert_eq!(nonce, U256::from(100));
    assert_eq!(deadline, U256::from(T0 + 3 * DAY));
    assert_eq!(
        err_name(submit(&vm, &mut d, &f["submitOld"]).unwrap_err()),
        "StaleState"
    );

    // Bob answers a day later with the latest state: it replaces the old one, the deadline stays.
    vm.set_block_timestamp(T0 + DAY);
    submit(&vm, &mut d, &f["submitLatest"]).unwrap();
    let (_, nonce, state_hash, deadline) = d.dispute_of(cn);
    assert_eq!(nonce, U256::from(200));
    assert_eq!(state_hash, num(&f["submitLatest"]["signals"][3]));
    assert_eq!(
        deadline,
        U256::from(T0 + 3 * DAY),
        "replacing a pending state never moves its deadline"
    );
    assert_eq!(
        err_name(submit(&vm, &mut d, &f["submitOld"]).unwrap_err()),
        "StaleState"
    );

    vm.set_block_timestamp(T0 + 3 * DAY - 1);
    assert_eq!(
        err_name(finalize(&mut d, &f["finalize"]).unwrap_err()),
        "DeadlineNotReached"
    );
    vm.set_block_timestamp(T0 + 3 * DAY);
    finalize(&mut d, &f["finalize"]).unwrap();
    assert!(d.is_finalized(cn));
    assert!(!d.dispute_of(cn).0);

    assert_eq!(
        err_name(finalize(&mut d, &f["finalize"]).unwrap_err()),
        "ChannelAlreadyFinalized"
    );
    assert_eq!(
        err_name(submit(&vm, &mut d, &f["submitLatest"]).unwrap_err()),
        "ChannelAlreadyFinalized"
    );
}

#[test]
fn finalize_settles_only_the_pending_state() {
    let vm = TestVM::default();
    let mut d = setup(&vm);
    let f = fixture();
    assert_eq!(
        err_name(finalize(&mut d, &f["finalize"]).unwrap_err()),
        "NoPendingDispute"
    );
    submit(&vm, &mut d, &f["submitOld"]).unwrap();
    vm.set_block_timestamp(T0 + 3 * DAY);
    // The finalize proof settles the latest state, but only the old one is pending.
    assert_eq!(
        err_name(finalize(&mut d, &f["finalize"]).unwrap_err()),
        "StateMismatch"
    );
}

#[test]
fn finalize_rejects_tampered_ciphertexts_and_proofs() {
    let vm = TestVM::default();
    let mut d = setup(&vm);
    let f = fixture();
    submit(&vm, &mut d, &f["submitLatest"]).unwrap();
    vm.set_block_timestamp(T0 + 3 * DAY);
    let v = &f["finalize"];

    let mut cts = bytes(&v["ciphertexts"]).to_vec();
    cts[0] ^= 1;
    assert_eq!(
        err_name(
            d.finalize(words(&v["proof"]), words(&v["signals"]), Bytes::from(cts))
                .unwrap_err()
        ),
        "InvalidExtData"
    );

    let mut proof: [U256; 8] = words(&v["proof"]);
    proof[7] += U256::from(1);
    assert_eq!(
        err_name(
            d.finalize(proof, words(&v["signals"]), bytes(&v["ciphertexts"]))
                .unwrap_err()
        ),
        "InvalidProof"
    );

    let mut signals: [U256; 9] = words(&v["signals"]);
    signals[4] += U256::from(1);
    assert_eq!(
        err_name(
            d.finalize(words(&v["proof"]), signals, bytes(&v["ciphertexts"]))
                .unwrap_err()
        ),
        "InvalidProof",
        "payout notes are bound"
    );

    finalize(&mut d, v).unwrap();
}

#[test]
fn submissions_need_a_known_root_a_valid_window_and_a_valid_proof() {
    let vm = TestVM::default();
    let mut d = setup(&vm);
    let f = fixture();
    let v = &f["submitOld"];
    let signals: [U256; 5] = words(&v["signals"]);

    pool_knows(&vm, signals[0], false);
    assert_eq!(
        err_name(d.submit_state(words(&v["proof"]), signals).unwrap_err()),
        "UnknownRoot"
    );

    for window in [MIN_WINDOW - 1, MAX_WINDOW + 1] {
        let mut s = signals;
        s[4] = U256::from(window);
        pool_knows(&vm, s[0], true);
        assert_eq!(
            err_name(d.submit_state(words(&v["proof"]), s).unwrap_err()),
            "InvalidWindow"
        );
    }

    let mut s = signals;
    s[2] += U256::from(1);
    pool_knows(&vm, s[0], true);
    assert_eq!(
        err_name(d.submit_state(words(&v["proof"]), s).unwrap_err()),
        "InvalidProof",
        "the nonce is bound"
    );
    assert!(
        !d.dispute_of(channel_nullifier(v)).0,
        "nothing was recorded"
    );
}

#[test]
fn a_contribution_left_out_of_the_final_state_is_reclaimed_after_finalization() {
    let vm = TestVM::default();
    let mut d = setup(&vm);
    let f = fixture();
    let cn = channel_nullifier(&f["submitState0"]);

    assert_eq!(
        err_name(reclaim(&mut d, &f["reclaim"]).unwrap_err()),
        "ChannelNotFinalized"
    );
    submit(&vm, &mut d, &f["submitState0"]).unwrap();
    assert_eq!(
        err_name(reclaim(&mut d, &f["reclaim"]).unwrap_err()),
        "ChannelNotFinalized"
    );
    vm.set_block_timestamp(T0 + 3 * DAY);
    finalize(&mut d, &f["finalizeState0"]).unwrap();
    assert!(d.is_finalized(cn));
    reclaim(&mut d, &f["reclaim"]).unwrap();
}

#[test]
fn reports_when_the_pool_refuses_the_settlement() {
    let vm = TestVM::default();
    let mut d = setup(&vm);
    let f = fixture();
    submit(&vm, &mut d, &f["submitLatest"]).unwrap();
    vm.set_block_timestamp(T0 + 3 * DAY);
    let v = &f["finalize"];
    let s: [U256; 9] = words(&v["signals"]);
    let data = IPool::settleCall {
        root: s[0],
        nf0: s[2],
        nf1: s[3],
        outputs: [s[4], s[5], s[6]],
        ciphertexts: bytes(&v["ciphertexts"]),
    }
    .abi_encode();
    vm.mock_call(POOL, data, U256::ZERO, Err(alloc::vec![]));
    assert_eq!(
        err_name(finalize(&mut d, v).unwrap_err()),
        "SettlementFailed"
    );
}

#[test]
fn window_bounds_are_three_to_seven_days() {
    let vm = TestVM::default();
    let d = setup(&vm);
    assert_eq!(d.window_bounds(), (3 * DAY, 7 * DAY));
}
