// Compiles the circuits, runs the Groth16 circuit-specific setup (phase 2) on top of the PSE
// perpetual powers-of-tau (phase 1), and publishes the artifacts:
//   circuits/build/<name>/            r1cs, wasm, sym, zkey, verification key
//   packages/framework/artifacts/     <name>.wasm + <name>.zkey for proving
//   contracts/pool/src/generated/vk.rs verifying keys for the Stylus verifier
// Rebuilds only what changed (keyed by a hash of the circuit sources). `--fresh-setup` forces a new setup.
import { execFileSync } from 'node:child_process';
import { createHash, randomBytes } from 'node:crypto';
import { copyFileSync, existsSync, mkdirSync, readFileSync, readdirSync, writeFileSync } from 'node:fs';
import { homedir } from 'node:os';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import * as snarkjs from 'snarkjs';

const here = dirname(fileURLToPath(import.meta.url));
const circuitsDir = resolve(here, '..');
const repo = resolve(circuitsDir, '..');
const buildDir = join(circuitsDir, 'build');
const frameworkArtifacts = join(repo, 'packages/framework/artifacts');
const generatedRust = join(repo, 'contracts/pool/src/generated');

export const CIRCUITS = ['transfer', 'finalize', 'reclaim', 'submit_state'] as const;
const PTAU = process.env.OCCULTA_PTAU ?? join(homedir(), '.local/share/occulta-tools/ptau/ppot_0080_17.ptau');

const freshSetup = process.argv.includes('--fresh-setup');

function sourcesHash(): string {
  const hash = createHash('sha256');
  const walk = (dir: string): void => {
    for (const entry of readdirSync(dir, { withFileTypes: true }).sort((a, b) => a.name.localeCompare(b.name))) {
      const path = join(dir, entry.name);
      if (entry.isDirectory()) walk(path);
      else if (entry.name.endsWith('.circom')) hash.update(path).update(readFileSync(path));
    }
  };
  walk(join(circuitsDir, 'src'));
  hash.update(JSON.parse(readFileSync(join(repo, 'node_modules/circomlib/package.json'), 'utf8')).version);
  return hash.digest('hex');
}

function compile(name: string, out: string): void {
  mkdirSync(out, { recursive: true });
  execFileSync(
    'circom',
    [join(circuitsDir, 'src', `${name}.circom`), '--O2', '--r1cs', '--wasm', '--sym', '-l', join(repo, 'node_modules'), '-o', out],
    { stdio: ['ignore', 'ignore', 'inherit'] },
  );
  // circom writes the witness generator to <out>/<name>_js/<name>.wasm
  copyFileSync(join(out, `${name}_js`, `${name}.wasm`), join(out, `${name}.wasm`));
}

async function setup(name: string, out: string): Promise<void> {
  const zkey0 = join(out, `${name}_0000.zkey`);
  await snarkjs.zKey.newZKey(join(out, `${name}.r1cs`), PTAU, zkey0);
  await snarkjs.zKey.contribute(zkey0, join(out, `${name}.zkey`), 'occulta-team', randomBytes(64).toString('hex'));
  const vk = await snarkjs.zKey.exportVerificationKey(join(out, `${name}.zkey`));
  writeFileSync(join(out, `${name}.vkey.json`), JSON.stringify(vk, null, 2));
}

interface VerificationKey {
  nPublic: number;
  vk_alpha_1: string[];
  vk_beta_2: string[][];
  vk_gamma_2: string[][];
  vk_delta_2: string[][];
  IC: string[][];
}

const word = (v: string): string => BigInt(v).toString(16).padStart(64, '0');
const bytesLiteral = (hex: string): string => `hex!("${hex}")`;
// EVM precompile encodings: G1 = x || y; G2 = x_c1 || x_c0 || y_c1 || y_c0.
const g1 = (p: string[]): string => bytesLiteral(word(p[0] as string) + word(p[1] as string));
const g2 = (p: string[][]): string =>
  bytesLiteral(word((p[0] as string[])[1] as string) + word((p[0] as string[])[0] as string) + word((p[1] as string[])[1] as string) + word((p[1] as string[])[0] as string));

function rustVerifyingKeys(): string {
  const parts = CIRCUITS.map((name) => {
    const vk = JSON.parse(readFileSync(join(buildDir, name, `${name}.vkey.json`), 'utf8')) as VerificationKey;
    const ident = name.toUpperCase();
    return [
      `pub const ${ident}_IC: [[u8; 64]; ${vk.IC.length}] = [`,
      ...vk.IC.map((p) => `    ${g1(p)},`),
      `];`,
      `pub const ${ident}: VerifyingKey = VerifyingKey {`,
      `    alpha: ${g1(vk.vk_alpha_1)},`,
      `    beta: ${g2(vk.vk_beta_2)},`,
      `    gamma: ${g2(vk.vk_gamma_2)},`,
      `    delta: ${g2(vk.vk_delta_2)},`,
      `    ic: &${ident}_IC,`,
      `};`,
    ].join('\n');
  });
  return [
    '// @generated by circuits/scripts/build.ts from the Groth16 setup. Do not edit.',
    'use crate::groth16::VerifyingKey;',
    'use hex_literal::hex;',
    '',
    ...parts,
    '',
  ].join('\n');
}

async function main(): Promise<void> {
  if (!existsSync(PTAU)) throw new Error(`powers of tau not found at ${PTAU} (run scripts/setup-tools.sh)`);
  const hash = sourcesHash();
  for (const name of CIRCUITS) {
    const out = join(buildDir, name);
    const stamp = join(out, 'sources.sha256');
    const upToDate = existsSync(stamp) && readFileSync(stamp, 'utf8') === hash && existsSync(join(out, `${name}.zkey`));
    if (upToDate && !freshSetup) {
      process.stdout.write(`${name}: up to date\n`);
      continue;
    }
    process.stdout.write(`${name}: compiling\n`);
    compile(name, out);
    process.stdout.write(`${name}: groth16 setup\n`);
    await setup(name, out);
    writeFileSync(stamp, hash);
  }

  mkdirSync(frameworkArtifacts, { recursive: true });
  for (const name of CIRCUITS) {
    copyFileSync(join(buildDir, name, `${name}.wasm`), join(frameworkArtifacts, `${name}.wasm`));
    copyFileSync(join(buildDir, name, `${name}.zkey`), join(frameworkArtifacts, `${name}.zkey`));
    copyFileSync(join(buildDir, name, `${name}.vkey.json`), join(frameworkArtifacts, `${name}.vkey.json`));
  }
  mkdirSync(generatedRust, { recursive: true });
  writeFileSync(join(generatedRust, 'vk.rs'), rustVerifyingKeys());
  process.stdout.write('artifacts published\n');
}

await main();
// snarkjs keeps its worker threads alive; end explicitly once everything is written.
process.exit(0);
