//! Native tests: the pool replays real proofs generated by contracts/scripts/fixtures.ts.

use super::*;
use stylus_sdk::testing::TestVM;

const USDG: Address = Address::repeat_byte(0x55);
const VERIFIER: Address = Address::repeat_byte(0x01);
const HASHER: Address = Address::repeat_byte(0x02);
const DISPUTES: Address = Address::repeat_byte(0x03);

fn fixture() -> serde_json::Value {
    let path = std::path::Path::new(env!("CARGO_MANIFEST_DIR"))
        .join("../../circuits/build/fixtures/pool.json");
    let text = std::fs::read_to_string(&path)
        .unwrap_or_else(|_| panic!("missing {} (run `npm run setup`)", path.display()));
    serde_json::from_str(&text).unwrap()
}

fn num(v: &serde_json::Value) -> U256 {
    U256::from_str_radix(v.as_str().unwrap(), 10).unwrap()
}

fn words<const N: usize>(v: &serde_json::Value) -> [U256; N] {
    v.as_array()
        .unwrap()
        .iter()
        .map(num)
        .collect::<Vec<_>>()
        .try_into()
        .unwrap()
}

fn hex_bytes(v: &serde_json::Value) -> Bytes {
    Bytes::from(alloy_primitives::hex::decode(v.as_str().unwrap()).unwrap())
}

struct Tx {
    proof: [U256; 8],
    signals: [U256; 9],
    recipient: Address,
    ciphertexts: Bytes,
}

fn tx(v: &serde_json::Value) -> Tx {
    Tx {
        proof: words(&v["proof"]),
        signals: words(&v["signals"]),
        recipient: v["recipient"].as_str().unwrap().parse().unwrap(),
        ciphertexts: hex_bytes(&v["ciphertexts"]),
    }
}

fn setup(vm: &TestVM) -> Pool {
    let mut pool = Pool::from(vm);
    pool.initialize(USDG, VERIFIER, HASHER, DISPUTES).unwrap();
    pool
}

fn deposit_fixture(vm: &TestVM, pool: &mut Pool, f: &serde_json::Value) {
    for d in f["deposits"].as_array().unwrap() {
        vm.set_value(num(&d["amount"]));
        pool.deposit(
            Address::ZERO,
            num(&d["amount"]),
            num(&d["inner"]),
            hex_bytes(&d["ciphertext"]),
        )
        .unwrap();
    }
    vm.set_value(U256::ZERO);
}

fn transact(pool: &mut Pool, t: &Tx) -> Result<(), PoolError> {
    pool.transact(t.proof, t.signals, t.recipient, t.ciphertexts.clone())
}

fn err_name(e: PoolError) -> String {
    let debug = format!("{e:?}");
    debug.split('(').next().unwrap().to_string()
}

#[test]
fn initializes_once_and_refuses_use_before() {
    let vm = TestVM::default();
    let mut pool = Pool::from(&vm);
    let f = fixture();
    assert_eq!(
        err_name(transact(&mut pool, &tx(&f["transfer"])).unwrap_err()),
        "NotInitialized"
    );
    pool.initialize(USDG, VERIFIER, HASHER, DISPUTES).unwrap();
    assert_eq!(
        err_name(
            pool.initialize(USDG, VERIFIER, HASHER, DISPUTES)
                .unwrap_err()
        ),
        "AlreadyInitialized"
    );
    assert_eq!(pool.root(), ZEROS[TREE_DEPTH]);
    assert!(pool.is_known_root(ZEROS[TREE_DEPTH]));
    assert!(!pool.is_known_root(U256::ZERO));
}

#[test]
fn replays_deposit_transfer_and_withdrawal_with_real_proofs() {
    let vm = TestVM::default();
    let mut pool = setup(&vm);
    let f = fixture();

    deposit_fixture(&vm, &mut pool, &f);
    let deposit_logs = vm.get_emitted_logs();
    assert_eq!(deposit_logs.len(), 1, "one NewCommitment event");
    assert_eq!(
        U256::from_be_bytes(deposit_logs[0].0[1].0),
        num(&f["deposits"][0]["commitment"])
    );

    let transfer = tx(&f["transfer"]);
    assert!(
        pool.is_known_root(transfer.signals[0]),
        "the proof's root is the pool's root after the deposit"
    );
    transact(&mut pool, &transfer).unwrap();
    assert!(pool.is_spent(transfer.signals[4]) && pool.is_spent(transfer.signals[5]));
    assert_eq!(
        vm.get_emitted_logs().len(),
        1 + 2 + 3,
        "two nullifiers and three commitments"
    );

    let withdrawal = tx(&f["withdrawal"]);
    transact(&mut pool, &withdrawal).unwrap();
    assert_eq!(
        pool.root(),
        num(&f["finalRoot"]),
        "on-chain tree matches the framework's tree"
    );

    // Replaying either transaction fails: its nullifiers are spent.
    assert_eq!(
        err_name(transact(&mut pool, &transfer).unwrap_err()),
        "NullifierAlreadySpent"
    );
    assert_eq!(
        err_name(transact(&mut pool, &withdrawal).unwrap_err()),
        "NullifierAlreadySpent"
    );
}

#[test]
fn rejects_tampered_transactions() {
    let vm = TestVM::default();
    let mut pool = setup(&vm);
    let f = fixture();
    deposit_fixture(&vm, &mut pool, &f);
    let good = tx(&f["transfer"]);

    let mut t = tx(&f["transfer"]);
    t.signals[0] += U256::from(1);
    assert_eq!(
        err_name(transact(&mut pool, &t).unwrap_err()),
        "UnknownRoot"
    );

    let mut t = tx(&f["transfer"]);
    t.signals[5] = t.signals[4];
    assert_eq!(
        err_name(transact(&mut pool, &t).unwrap_err()),
        "DuplicateNullifier"
    );

    let mut t = tx(&f["transfer"]);
    let mut cts = t.ciphertexts.to_vec();
    cts[10] ^= 1;
    t.ciphertexts = Bytes::from(cts);
    assert_eq!(
        err_name(transact(&mut pool, &t).unwrap_err()),
        "InvalidExtData",
        "ciphertexts are bound"
    );

    let mut t = tx(&f["transfer"]);
    t.ciphertexts = Bytes::from(t.ciphertexts[..503].to_vec());
    assert_eq!(
        err_name(transact(&mut pool, &t).unwrap_err()),
        "InvalidExtData"
    );

    let mut t = tx(&f["transfer"]);
    t.recipient = Address::repeat_byte(0x99);
    assert_eq!(
        err_name(transact(&mut pool, &t).unwrap_err()),
        "InvalidExtData",
        "recipient is bound"
    );

    let mut t = tx(&f["transfer"]);
    t.proof[2] += U256::from(1);
    assert_eq!(
        err_name(transact(&mut pool, &t).unwrap_err()),
        "InvalidProof"
    );

    let mut t = tx(&f["transfer"]);
    t.signals[6] += U256::from(1);
    assert_eq!(
        err_name(transact(&mut pool, &t).unwrap_err()),
        "InvalidProof",
        "outputs are bound"
    );

    let mut t = tx(&f["transfer"]);
    t.signals[1] = MAX_AMOUNT + U256::from(1);
    assert_eq!(
        err_name(transact(&mut pool, &t).unwrap_err()),
        "InvalidAmount"
    );

    // Nothing above changed the pool: the honest transaction still goes through.
    transact(&mut pool, &good).unwrap();
}

#[test]
fn withdrawals_pay_only_allowed_tokens() {
    let vm = TestVM::default();
    let mut pool = setup(&vm);
    let f = fixture();
    deposit_fixture(&vm, &mut pool, &f);
    transact(&mut pool, &tx(&f["transfer"])).unwrap();
    let mut t = tx(&f["withdrawal"]);
    t.signals[2] = U256::from(0x1234);
    assert_eq!(
        err_name(transact(&mut pool, &t).unwrap_err()),
        "TokenNotAllowed"
    );
}

#[test]
fn deposit_checks() {
    let vm = TestVM::default();
    let mut pool = setup(&vm);
    let ct = Bytes::from(alloc::vec![7u8; CIPHERTEXT_SIZE]);

    vm.set_value(U256::from(5));
    assert_eq!(
        err_name(
            pool.deposit(Address::ZERO, U256::from(6), U256::from(1), ct.clone())
                .unwrap_err()
        ),
        "InvalidValue"
    );
    assert_eq!(
        err_name(
            pool.deposit(
                Address::ZERO,
                U256::from(5),
                U256::from(1),
                Bytes::from(alloc::vec![7u8; 167])
            )
            .unwrap_err()
        ),
        "InvalidCiphertext"
    );
    assert_eq!(
        err_name(
            pool.deposit(Address::ZERO, U256::from(5), SCALAR_MODULUS, ct.clone())
                .unwrap_err()
        ),
        "InvalidField"
    );
    assert_eq!(
        err_name(
            pool.deposit(
                Address::repeat_byte(0x77),
                U256::from(5),
                U256::from(1),
                ct.clone()
            )
            .unwrap_err()
        ),
        "TokenNotAllowed"
    );
    assert_eq!(
        err_name(
            pool.deposit(USDG, U256::from(5), U256::from(1), ct.clone())
                .unwrap_err()
        ),
        "InvalidValue",
        "no ETH with a token deposit"
    );

    vm.set_value(MAX_AMOUNT + U256::from(1));
    assert_eq!(
        err_name(
            pool.deposit(
                Address::ZERO,
                MAX_AMOUNT + U256::from(1),
                U256::from(1),
                ct.clone()
            )
            .unwrap_err()
        ),
        "InvalidAmount"
    );
    vm.set_value(U256::ZERO);
    assert_eq!(
        err_name(
            pool.deposit(Address::ZERO, U256::ZERO, U256::from(1), ct.clone())
                .unwrap_err()
        ),
        "InvalidAmount"
    );

    // The commitment is computed from what was received: H(0 * 2^64 + 5, inner).
    vm.set_value(U256::from(5));
    pool.deposit(Address::ZERO, U256::from(5), U256::from(1), ct)
        .unwrap();
    let logged = U256::from_be_bytes(vm.get_emitted_logs()[0].0[1].0);
    assert_eq!(
        logged,
        occulta_core::poseidon::hash2(U256::from(5), U256::from(1))
    );
}

#[test]
fn settle_is_only_for_the_disputes_contract() {
    let vm = TestVM::default();
    let mut pool = setup(&vm);
    let root = pool.root();
    let cts = Bytes::from(alloc::vec![1u8; 3 * CIPHERTEXT_SIZE]);
    let outputs = [U256::from(1), U256::from(2), U256::from(3)];
    assert_eq!(
        err_name(
            pool.settle(root, U256::from(10), U256::from(11), outputs, cts.clone())
                .unwrap_err()
        ),
        "Unauthorized"
    );

    vm.set_sender(DISPUTES);
    pool.settle(root, U256::from(10), U256::from(11), outputs, cts.clone())
        .unwrap();
    assert!(pool.is_spent(U256::from(10)) && pool.is_spent(U256::from(11)));
    assert_ne!(pool.root(), root);
    assert_eq!(
        err_name(
            pool.settle(root, U256::from(10), U256::from(12), outputs, cts.clone())
                .unwrap_err()
        ),
        "NullifierAlreadySpent"
    );
    assert_eq!(
        err_name(
            pool.settle(
                root,
                U256::from(13),
                U256::from(14),
                outputs,
                Bytes::from(alloc::vec![1u8; 10])
            )
            .unwrap_err()
        ),
        "InvalidCiphertext"
    );
}

#[test]
fn keeps_exactly_the_last_100_roots() {
    let vm = TestVM::default();
    let mut pool = setup(&vm);
    vm.set_sender(DISPUTES);
    let cts = Bytes::from(alloc::vec![1u8; 3 * CIPHERTEXT_SIZE]);
    let mut roots = alloc::vec![pool.root()];
    for i in 0..ROOT_HISTORY {
        let nf = U256::from(1000 + 2 * i);
        pool.settle(
            pool.root(),
            nf,
            nf + U256::from(1),
            [U256::from(i + 1), U256::from(i + 2), U256::from(i + 3)],
            cts.clone(),
        )
        .unwrap();
        roots.push(pool.root());
    }
    // 101 roots were recorded; the ring holds 100, so the first (empty-tree) root is forgotten.
    assert!(!pool.is_known_root(roots[0]));
    for r in &roots[1..] {
        assert!(pool.is_known_root(*r));
    }
}
